# Syntax highlighting
highlighter:         pygments

# Setup
title:               Dat Duy Doan
tagline:             Digital Designer
description:         Dat is a designer with empathy for the users, the web and technology. His is a Digital Designer live in Sydney and like many design things, especially website.
keywords:            dat, duy, doan, digital, designer, sydney, australia, website, design, online, conversion, marketing, optimisation, campaign
url:                 http://hellodat.com
baseurl:             /

# Social Network
footer-links:
  twitter:           dat
  github:            datdoan

# Google Analytics
google_analytics:    UA-50186440-5

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

exclude:
    - node_modules
